title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /initramfs-linux.img
options rd.luks.name=UUID_LUKS2=cryptroot root=/dev/mapper/cryptroot rootflags=subvol=@ rd.luks.options=UUID_LUKS2=discard i915.force_probe=!a7a1 xe.force_probe=a7a1 rw quiet iwlwifi.disable_11ax=1 acpi.ec_no_wakeup=1
